version: "3.9"

services: 
  frontend:
    depends_on: 
      - document_builder
    image: flobbe9/word_light_frontend
    container_name: frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
      # replace prod ip for local testing
      - API_HOST=localhost
    restart: on-failure

  gateway:
    image: flobbe9/word_light_gateway
    container_name: gateway
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      - DOCUMENT_BUILDER_HOST=api
      # replace prod ip for local testing
      - HOST=localhost
    restart: on-failure

  api:
    depends_on: 
      - gateway
      - db
    image: flobbe9/word_light_document_builder
    container_name: ${API_NAME}
    ports:
      - ${PORT}:${PORT}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      # replace prod ip for local testing
      - HOST=localhost
    healthcheck:
      test: wget --no-verbose --tries=1 --spider ${BASE_URL} || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure

  db:
    image: mysql
    container_name: db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysql -u${SPRING_DATASOURCE_USERNAME} -p${SPRING_DATASOURCE_PASSWORD}
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    restart: on-failure