version: "3.9"

services:
  db:
      image: mysql
      container_name: db
      ports:
          - ${DB_PORT}:${DB_PORT}
      environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
        MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        TZ: Europe/Berlin

  api:
      depends_on: 
        - db
      build: .
      container_name: api
      ports: 
          - ${API_PORT}:${API_PORT}
      env_file: .env
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://db:${DB_PORT}/${DB_NAME}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}