version: "3.9"

services:
  db:
    image: mysql
    container_name: db
    ports:
        - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Europe/Berlin

  document_builder:
    depends_on: 
      - db
    build: .
    image: flobbe9/word_light_document_builder
    container_name: ${API_NAME}
    ports: 
        - ${API_PORT}:${API_PORT}
    # use ./.env as .env file for application (not only for docker-compose file)
    env_file: .env
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://db:${DB_PORT}/${DB_NAME}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}