version: "3.9"

services:
    db:
        image: mysql
        container_name: db
        ports:
            - 3306:3306
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: ${DB_NAME}
          TZ: Europe/Berlin

    # mailserver:
    #     image: maildev/maildev
    #     container_name: maildev_server
    #     ports:
    #         - 1080:1080
    #         - 1025:1025
    document_builder:
        depends_on: 
          - db
          # - mailserver
        build: .
        container_name: document_builder
        ports: 
            - ${API_PORT}:${API_PORT}
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${DB_NAME}
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=
            - SPRING_JPA_HIBERNATE_DDL_AUTO=create