version: "3.9"

services: 
  frontend:
    image: flobbe9/vorspiel_frontend
    container_name: frontend
    env_file: .env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
      
  db:
    image: mysql
    container_name: db
    ports:
        - ${DB_PORT}:${DB_PORT}
    env_file: .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}

  # mailserver:
  #     image: maildev/maildev
  #     container_name: mail_server_test
        # env_file: .env
  #     ports:
  #         - ${MAIL_INBOX_PORT}:${MAIL_INBOX_PORT} # mail inbox port (ui)
  #         - ${MAIL_SERVER_PORT}:${MAIL_SERVER_PORT} # mail server port

  backend:
    depends_on: 
      - db
      # - mailserver
    build: .
    image: flobbe9/vorspiel_backend
    container_name: ${API_NAME}
    ports:
      - ${API_PORT}:${API_PORT}
    env_file: .env
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://db:${DB_PORT}/${DB_NAME}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
