version: "3.9"

services:
    db:
        image: mysql
        container_name: vorspiel_db
        ports:
            - 3306:3306
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: vorspiel

    # mailserver:
    #     image: maildev/maildev
    #     container_name: vorspiel_mail_server_test
    #     ports:
    #         - 1080:1080
    #         - 1025:1025
    api:
      depends_on: 
        - db
        # - mailserver
      build: .
      container_name: vorspiel_backend
      ports: 
          - 4001:4001
      environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/vorspiel
          - SPRING_DATASOURCE_USERNAME=root
          - SPRING_DATASOURCE_PASSWORD=
          - SPRING_JPA_HIBERNATE_DDL_AUTO=create