version: "3.9"

services:
  db:
    image: mysql
    container_name: ${DB_NAME}_db
    ports:
        - ${DB_PORT}:${DB_PORT}
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      TZ: Europe/Berlin