server:
    port: 4001
    error:
        include-message: always

spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    config:
        # include .env file
        import: optional:file:.env[.properties]

## h2
# spring:
#     datasource:
#         url: jdbc:h2:mem:vorspiel
#     jpa:
#         database-platform: org.hibernate.dialect.H2Dialect
#     h2:
#         console:
#             enabled: true
#             path: /h2