server:
    port: ${API_PORT}
    error:
        include-message: always
    servlet:
        session:
            timeout: 15m

    ### SSL
    ssl:
        key-store-type: ${SSL_KEY_STORE_TYPE}
        key-store: ${SSL_KEY_STORE}
        key-store-password: ${SSL_KEY_STORE_PASSWORD}
        key-alias: ${SSL_KEY_ALIAS}
        enabled: ${SSL_ENABLED}

spring:
    application:
        name: ${API_NAME}
    servlet:
        multipart:
            # increase max file size for request payload
            max-file-size: 10MB
            max-request-size: 10MB
    config:
        # include .env file
        import: optional:file:.env[.properties]

    ### DB
    datasource:
        url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
        # url: jdbc:h2:mem:${DB_NAME}.db
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        # database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
        defer-datasource-initialization: true
        open-in-view: false
        # console: 
        #     enabled: true
        #     path: /h2

### Discovery Service
eureka:
    instance:
        hostname: ${API_HOST}
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: ${DISCOVERY_SERVICE_BASE_URL}/${DISCOVERY_SERVICE_MAPPING}