server:
    port: 4001
    error:
        include-message: always
    servlet:
        session:
            timeout: 15m
                ### SSL
    ssl:
        key-store-type: ${SSL_KEY_STORE_TYPE}
        key-store: ${SSL_KEY_STORE}
        key-store-password: ${SSL_KEY_STORE_PASSWORD}
        key-alias: ${SSL_KEY_ALIAS}
        enabled: ${SSL_ENABLED}

spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

    config:
        # include .env file
        import: optional:file:.env[.properties]

    ## db
    datasource:
        url: jdbc:mysql://localhost:3306/vorspiel
        # url: jdbc:h2:mem:vorspiel.db
        username: root
        password:
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        # database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        defer-datasource-initialization: true
        open-in-view: false
        # console: 
        #     enabled: true
        #     path: /h2