server:
    port: ${API_PORT}
    error:
        include-message: always
    servlet:
        session:
            timeout: 15m

spring:
    servlet:
        multipart:
            # increase max file size for request payload
            max-file-size: 10MB
            max-request-size: 10MB

    config:
        # include .env file
        import: optional:file:.env[.properties]

    ## db
    datasource:
        url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}
        # url: jdbc:h2:mem:${DB_NAME}.db
        username: root
        password:
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        # database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
        defer-datasource-initialization: true
        open-in-view: false
        # console: 
        #     enabled: true
        #     path: /h2