name: word-light_document_builder stage

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.12.0
        with: 
          distribution: 'temurin'
          java-version: '17'
      - name: Start db
        run: docker-compose -f 'docker-compose.db.yml' up -d      
      - run: gradle clean build