name: vorspiel_backend main

run-name: ${{ github.event.head_commit.message }}
on: 
  push: 
    branches:
      - main

env: 
    API_VERSION: 0.0.3
    PROJECT_NAME: vorspiel_backend
    GOOGLE_CLOUD_PROJECT_NAME: vorspiel-939791

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
      - run: gradle clean build
  
  push_to_DockerHub_and_Google_Cloud:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag image with old version
        run: docker tag flobbe9/$PROJECT_NAME:latest flobbe9/$PROJECT_NAME:$API_VERSION

      - name: Push image with old version
        run: docker image push flobbe9/$PROJECT_NAME:$API_VERSION
    
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: flobbe9/$PROJECT_NAME:latest

      - name: Tag Google Cloud image 
        run: docker tag flobbe9/$PROJECT_NAME:latest gcr.io/$GOOGLE_CLOUD_PROJECT_NAME/$PROJECT_NAME:latest

      - name: Push Google Cloud image
        run: docker image push gcr.io/$GOOGLE_CLOUD_PROJECT_NAME/$PROJECT_NAME:latest